version: "3.4"

networks:
  auth_service:
  repo_rangler_proxy:
    external:
      name: repo_rangler_proxy

volumes:
  auth_service:

services:
  auth_service_nginx:
    container_name: reporangler_auth_service_nginx
    image: reporangler/auth_service_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    networks:
      - repo_rangler_proxy
      - auth_service
    environment:
      - VIRTUAL_HOST=auth.reporangler.develop

  auth_service_phpfpm:
    container_name: reporangler_auth_service_phpfpm
    image: reporangler/auth_service_phpfpm
    build:
      context: .
      dockerfile: docker/phpfpm/Dockerfile
    networks:
      - auth_service
    volumes:
      - $PWD:/www
    env_file:
      - $PWD/.env

  auth_service_postgres:
    container_name: reporangler_auth_service_postgres
    image: postgres:alpine
    ports:
      - 5430:5432
    networks:
      - auth_service
    volumes:
      - auth_service:/var/lib/postgresql/data
    env_file:
      - $PWD/.env
